### ISSUE TITLE
Autoscaling doesn't seem to be working

### ISSUE THREAD

**Issue by banderson5144** [SFDO-Tooling/MetaCI#1589]
I think have the correct config variables set up:

![image](https://user-images.githubusercontent.com/2395774/95749082-0468ab80-0c69-11eb-9787-884d155509dc.png)

and I also have my `HEROKU_TOKEN` set up as well, but I still see some of my builds wait for previous builds to complete. Is there something I am missing?

**Comment by davisagli** [comment]
There are a few other requirements for autoscaling to work:
1. Make sure you have DJANGO_SETTINGS_MODULE set to config.settings.production
2. Set the HEROKU_APP_NAME config var to the name of the app
3. Make sure you add the RepeatableJob mentioned in https://github.com/SFDO-Tooling/MetaCI#automatic-scaling (without this it will scale up as builds are queued, but not down once the queue is empty).

If it continues to not work, maybe there's a clue in the app log about what's not working. Keep in mind that it can take a couple minutes for new dynos to start, particularly if you're using a Private Space.

> I still see some of my builds wait for previous builds to complete.

Note that in addition to the constraint based on how many worker dynos are running, MetaCI has a mechanism for locking persistent orgs so that only one build can run on a particular org at once.

**Comment by banderson5144** [comment]
Hey @davisagli thanks for the help. I just made the change for point 1, and I already had my HEROKU_APP_NAME setup as well. The thing I am not understanding is point 3, where do you I actually set up the Repeatable Job?

**Comment by davisagli** [comment]
In the Django admin UI.

**Comment by banderson5144** [comment]
:facepalm: thank you @davisagli , taking care of this now.

**Comment by banderson5144** [comment]
@davisagli  I am getting this error:

`File "/app/metaci/build/autoscaling.py", line 179, in scale_max`
`assert target_workers >= 0`
`AssertionError`

**Comment by davisagli** [comment]
@banderson5144 It looks like this error can happen if you've set METACI_MAX_WORKERS to a higher value than Heroku's limit for dynos of a given type. We have some logic to try to catch that and scale only to the limit, but it looks like it might not be quite correct.

Can you show a screenshot of the "Resources" tab for your app, particularly the section that shows how many of each dyno type are running?

**Comment by banderson5144** [comment]
@davisagli 
![image](https://user-images.githubusercontent.com/2395774/96048117-28ccaf80-0e44-11eb-98cf-29b2bb9213e4.png)

**Comment by davisagli** [comment]
@banderson5144 According to https://devcenter.heroku.com/articles/limits#dyno-scale, with hobby dynos you can only run a single dyno of each process type. So in order to use autoscaling, you would need to switch to professional (standard or performance) dynos.

Also, the dev_worker process type is only designed for running in a single dyno. In order to use autoscaling you would instead run a single worker_short dyno, plus as many worker dynos as you want.

**Comment by banderson5144** [comment]
Ah understood @davisagli , so turn off the dev_worker, start the worker_short, and have them running as professional
