### ISSUE TITLE
Ability to push the latest code in a branch to an existing "saved" scratch org: re-run build on existing scratch org

### ISSUE THREAD

**Issue by cdcarter** [SFDO-Tooling/MetaCI#192]
to support QA/docs/UX using metaCI generated scratch orgs, they'd like the ability to push the latest code in a branch to an existing "saved" scratch org instead of having to create a new org

**Comment by annejackson** [comment]
Would love to see this as it would help save lots of time. Use case from QA:

1. User creates a scratch org off original pr
2. Issues were found with original PR, the developer makes changes
3. The PR is updated with the latest code, and the User wants those code changes into their existing scratch org. 

Right now- the user has to create a new org in MetaCi in order to check out those changes.
Desired- the user can just push the latest code from a branch into their already existing scratch org.

**Comment by davisagli** [comment]
Unfortunately there isn't a way to do this that will work reliably.
