### ISSUE TITLE
HELP : first steps configuring Services

### ISSUE THREAD

**Issue by RupertBarrow** [SFDO-Tooling/MetaCI#2799]
Hi,
I have deployed MetaCI to Heroku.
How do I configure Services in MetaCI, presumably as an admin : 
- dev hub service
- Github service (API connection and Webhooks)

Should I configure a Github app for MetaCI ?
What is the callback URL for Github webhooks ?

**Comment by davisagli** [comment]
# GitHub app

MetaCI uses a GitHub app to authenticate users via OAuth2, interact with the GitHub API, and receive webhooks for repository events.

Create a GitHub app to represent this instance of MetaCI with the following configuration:

* User authorization callback URL: https://*appname*.herokuapp.com/accounts/github/login/callback/ 
* Webhook URL: https://*appname*.herokuapp.com/webhook/github/push
* Set Webhook secret to a random string
* Permissions:
    * Contents: read/write
    * Pull requests: read/write
    * Commit statuses: read/write
    * Email addresses: read-only
* Events:
    * Push
* Click the button to generate a private key

Set the following config vars for the Heroku app:

* GITHUB_APP_ID: App ID for the GitHub app
* GITHUB_APP_KEY: Private key for the GitHub app
* GITHUB_WEBHOOK_SECRET: the secret that you entered for Webhook secret above
* GITHUB_CLIENT_ID: Client ID for the GitHub app
* GITHUB_CLIENT_SECRET: Client Secret for the GitHub app

# Dev Hub org

In order to create scratch orgs you’ll need an org with the Dev Hub feature enabled.

Add a new Profile named MetaCI by cloning the Minimum Access profile. Configure as follows:

* Enable CRUD permissions for the Scratch Org Info, Active Scratch Org, and Namespace Registry objects
* Enable the View Setup and Configuration permission. MetaCI needs this in order to check how much scratch org capacity is remaining.
* If MetaCI is running in a Heroku private space, add Login IP Ranges to only allow logins from the Space Outbound IPs for your Heroku private space

Add a new User using this profile.

# Salesforce connected app

MetaCI uses a Salesforce connected app to authenticate to Salesforce orgs (including the Dev Hub, scratch orgs created using the Dev Hub, and other orgs such as packaging orgs).

We suggest creating this connected app in the same org that is enabled as a Dev Hub. In Setup, go to App Manager and click the New Connected App button. Configure as follows:

* Callback URL: http://localhost:8080/callback and http://localhost:1717/OauthRedirect
* Use digital signatures: Check the box, obtain a certificate, and upload it here.
* Selected OAuth Scopes:
    * Full access (full)
    * Perform requests on your behalf at any time (refresh_token, offline_access)
    * Provide access to your data via the Web (web)

After saving, click the Manage button, then Edit Policies. Set Permitted Users to “Admin approved users are pre-authorized” and save. In the Profiles related list, click the Manage Profiles button. Select the MetaCI profile and save. This will ensure that only users with that profile can log in using this connected app.

Set the following config vars for the Heroku app:

* SFDX_CLIENT_ID: Consumer Key from the connected app
* SFDX_HUB_KEY: Private key that was used to sign the connected app’s Use digital signatures certificate
* SFDX_HUB_USERNAME: Username of the user with the MetaCI profile

DO NOT SET SFDX_CLIENT_SECRET

**Comment by RupertBarrow** [comment]
Thanks @davisagli !

Note to readers of the previous details :

Regarding : 
`GITHUB_APP_KEY: Private key for the GitHub app`
This means the contents of the PEM file which is downloaded when the key is generated. It is NOT the code after the `SHA256:`key name.
